added my profile
zero-to-mastery/ZtM-Job-Board pull request #1473
Opened 2020-10-01 14:20 UTC by valeriepadel

I've added my name to the list!

2020-10-01 17:33 UTC, abdus commented on src/assets/persons.js
> +  }
there's an error here

2020-10-01 17:33 UTC, abdus requested changes
fix errors

2020-10-02 17:12 UTC, valeriepadel commented on src/assets/persons.js
> +  }
Thank you @abdus 👍

2020-10-04 13:30 UTC, merged

2020-10-05 17:36 UTC, valeriepadel reviewed
add