Add my name to the list
zero-to-mastery/ZtM-Job-Board pull request #1660
Opened 2020-12-14 11:13 UTC by marinazzz

Hi, please add my name to the list. @alejandroiglesias

2020-12-18 05:14 UTC, abdus requested changes
Please don't delete `yarn.lock`

2020-12-18 19:00 UTC, marinazzz commented
> Please don't delete `yarn.lock`

Can you please take a look again, because yarn.lock file wasn't deleted. Thank you 
![Screenshot-ZtMJobBoard](https://user-images.githubusercontent.com/58655720/102650701-9c07e000-416b-11eb-8898-d17c48e8b8aa.png)

2020-12-20 08:40 UTC, abdus commented
sorry about that.

2020-12-20 08:40 UTC, abdus approved these changes

2020-12-20 08:41 UTC, merged