Added my profile ManideepPaul
zero-to-mastery/ZtM-Job-Board pull request #2656
Opened 2023-01-21 16:41 UTC by ManideepPaul

Added my profile details.

2023-01-22 18:23 UTC, ProsperousHeart requested changes
Please remove the brackets - these are not necessary

2023-01-22 18:23 UTC, ProsperousHeart commented on Submissions/@ManideepPaul.json
> +      "country": "[India]"
Please remove the brackets - these are not necessary

2023-01-23 03:15 UTC, closed without merging

2023-01-23 03:16 UTC, ManideepPaul commented
Creating new pull request

2023-01-23 15:57 UTC, ProsperousHeart commented
FYI - no need to close and recreate in the future. :)