abdelrahman mohamed
zero-to-mastery/ZtM-Job-Board pull request #2674
Opened 2023-02-01 14:53 UTC by abdelrahmanm98

2023-02-02 21:35 UTC, ProsperousHeart requested changes

2023-02-02 21:35 UTC, ProsperousHeart commented on Submissions/abdelrahman mohamed
> +  "name": "[Abdelrahman mohamed]",
please remove brackets

2023-02-26 17:17 UTC, ProsperousHeart commented
@abdelrahmanm98 looks good - but your last name isn't capitalized. We can approve if you'd like but thought I would ask

2023-03-13 16:57 UTC, MattCSmith approved these changes

2023-03-13 16:57 UTC, merged