Added aakib profile
zero-to-mastery/ZtM-Job-Board pull request #2691
Opened 2023-02-17 21:20 UTC by Aakibvah

Added my profile @aneagoie

2023-02-26 17:29 UTC, ProsperousHeart requested changes

2023-02-26 17:29 UTC, ProsperousHeart commented on Submissions/@Aakibvah.json
> +  "jobTitle": "Web Developer [React andNode]",
you have a space missing between andNode

2023-02-28 15:32 UTC, ProsperousHeart requested changes
sorry - missed some. My apologies

2023-02-28 15:32 UTC, ProsperousHeart commented on Submissions/@Aakibvah.json
> +    "country": "Canada]"
sorry I think I missed this one - please remove the ] from Canada, as I do not believe this will show up on the map

2023-02-28 15:32 UTC, ProsperousHeart commented on Submissions/@Aakibvah.json
> +  "jobTitle": "Web Developer [React and Node]",
I also don't think the brackets here will be an issue, but the README says not to include them - perhaps use () instead?

2023-02-28 15:37 UTC, ProsperousHeart commented
Looks great! I will merge but wanted to confirm - is your first name correct @Aakibvah? Or should there be a space in there before the middle capital A?

2023-02-28 15:39 UTC, Aakibvah commented
It's correct. you can merge it :)


On Tue, Feb 28, 2023 at 10:37 AM Kassandra Keeton ***@***.***>
wrote:

> Looks great! I will merge but wanted to confirm - is your first name
> correct @Aakibvah <https://github.com/Aakibvah>? Or should there be a
> space in there before the middle capital A?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zero-to-mastery/ZtM-Job-Board/pull/2691#issuecomment-1448398924>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU5GA56LH3LQ44CCLWMHWLTWZYLVDANCNFSM6AAAAAAU74G7FI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-28 15:41 UTC, merged