added profile
zero-to-mastery/ZtM-Job-Board pull request #2713
Opened 2023-03-05 16:07 UTC by MichaelBoitmann

thank you for adding my profile

2023-03-07 19:29 UTC, ProsperousHeart requested changes
Please remove the # for website, the @ in front of your file, and delete the file for nazmul that is not yours. Otherwise it will change this person's data.

2023-03-07 19:29 UTC, ProsperousHeart commented on Submissions/@michaelboitmann.json
> +      "website": "#",
please remove the #

2023-03-08 05:18 UTC, MichaelBoitmann commented
> Please remove the # for website, the @ in front of your file, and delete the file for nazmul that is not yours. Otherwise it will change this person's data.

Thanks. Sure i will the firstv2 items but for nazmul, that is the problem i have. After clone process it shows 2 names under naznul which are @nazmul and @Nazmul without ne doing anything in thise files. Tried to reclone it on 4 different folder but showing the same issue and I don't know why and how to fix it. Kindly delete those pull request i created as i created another one without Nazmul. Thanks

2023-03-09 08:53 UTC, MichaelBoitmann commented on Submissions/@michaelboitmann.json
> +      "website": "#",
done. thank you

2023-03-11 18:58 UTC, ProsperousHeart requested changes
you still seem to have an extra change outside of the file you're trying to submit. Please undo changes in that file as outlined in your [Files Changed](https://github.com/zero-to-mastery/ZtM-Job-Board/pull/2713/files)

2023-03-13 05:34 UTC, closed without merging