Added my name to the job portal list
zero-to-mastery/ZtM-Job-Board pull request #2717
Opened 2023-03-08 08:06 UTC by mailsg

Hi Team,

I have added my name to the job portal list. @dga 

Thanks.

2023-03-12 20:33 UTC, ProsperousHeart requested changes

2023-03-12 20:33 UTC, ProsperousHeart commented on Submissions/@mailsg.json
> +    "website": " ",
please remove the space

2023-03-12 20:33 UTC, ProsperousHeart commented on Submissions/@mailsg.json
> +  "jobTitle": "SRE/SDE",
we could leave this title, but just making a suggestion to spell them out

2023-03-13 04:12 UTC, mailsg commented
Hi,
I have made the changes as suggested. 
1. Removed the space from the website.
2. Defined the title.

Thanks.

2023-03-18 04:31 UTC, ProsperousHeart requested changes
everything looks good except for the @ in the file name - once that is removed this can be approved

2023-03-18 23:12 UTC, ProsperousHeart approved these changes
Approved! Thank you

2023-03-18 23:13 UTC, merged