adds berty's profile
zero-to-mastery/ZtM-Job-Board pull request #2727
Opened 2023-03-12 07:32 UTC by bertyruan

2023-03-12 20:44 UTC, ProsperousHeart requested changes
1 minor change requested

2023-03-12 20:44 UTC, ProsperousHeart commented on Submissions/bertyruan.json
> +    "website": "bertydev.com",
please provide the full site, including the http or https

2023-03-13 03:18 UTC, bertyruan commented
Hi @ProsperousHeart thanks for the comment. I've made the requested changes. Could you review my PR for one of ZtM's open source projects? I've been pinging the admins and project owners but no one's paying attention hahaha https://github.com/zero-to-mastery/CSS_Grid_LearnGame/pull/59

2023-03-31 17:15 UTC, ProsperousHeart approved these changes
Approved!

2023-03-31 17:15 UTC, merged