Added my job profile
zero-to-mastery/ZtM-Job-Board pull request #2743
Opened 2023-03-19 16:57 UTC by escapingSamsara

Please be so kind to add me to the ZtM Job Boad list !

2023-03-31 17:42 UTC, ProsperousHeart requested changes
please remove the package-lock.json ... this is not what is currently in the repo. If you would like it to be updated, please create an issue with what the change should be then create a PR tied to the issue.

As for your submission, please remove the @ - otherwise approved

2023-04-02 09:52 UTC, escapingSamsara reviewed
i deleted the package json (or didnt i ?)

and a

2023-04-26 19:03 UTC, ProsperousHeart requested changes
Aside from removing the package-lock.json from your git, your JSON data is approved.

2023-04-26 19:03 UTC, ProsperousHeart commented on package-lock.json
Please remove the deletion of this file from your git. If we approve this, it will be removed from the project completely.

2023-04-26 19:04 UTC, ProsperousHeart commented
> i deleted the package json (or didnt i ?)
> 
> and added the json file without @ and correct user image link

unfortunately deleting it will still update the project when approved and merged. It must be removed from your Git instance

2023-05-19 20:27 UTC, ProsperousHeart commented
@escapingSamsara - I have already provided the review. Is there a question about it?

2023-06-18 13:07 UTC, closed without merging