job search
zero-to-mastery/ZtM-Job-Board pull request #2816
Opened 2023-05-10 14:29 UTC by Emm-aan1

just added my name to submission

2023-05-19 20:34 UTC, ProsperousHeart requested changes
aside from suggested changes, please remove the `@` from filename as it needs to match you `Emm-aan1` username

2023-05-19 20:34 UTC, ProsperousHeart commented on Submissions/@emm-aan1.json
> +    "website": "emm-aan1.github.io/mine",
```suggestion
    "website": "https://emm-aan1.github.io/mine",
```

2023-05-19 20:34 UTC, ProsperousHeart commented on Submissions/@emm-aan1.json
> +}
```suggestion
}

```

2023-05-25 03:17 UTC, ProsperousHeart requested changes
Looks great except for the filename. Please ensure it matches your username exactly:  `Emm-aan1`

2023-05-25 20:41 UTC, closed without merging

2023-05-26 21:38 UTC, ProsperousHeart commented
FYI @Emm-aan1 you shouldn't need to close and open a new PR to complete this :)

2023-05-26 22:54 UTC, Emm-aan1 commented
I know. But for some reasons unknown to me, I couldn't push the changes so I was a bit confused