Create file Emm-aan1.json
zero-to-mastery/ZtM-Job-Board pull request #2831
Opened 2023-05-25 21:15 UTC by Emm-aan1

renamed the file to match my account name

2023-05-25 21:17 UTC, Emm-aan1 commented
My pull requests are not successful and u don't know why. Please help

2023-06-09 18:07 UTC, ProsperousHeart requested changes
Aside from missing the last `}` I believe this is ok. Please double check the main repo README.

2023-06-09 18:07 UTC, ProsperousHeart commented on Submissions/Emm-aan1.json
> +  }
```suggestion
  }
}

```

2023-06-10 16:18 UTC, ProsperousHeart approved these changes
Approved!

2023-06-10 16:18 UTC, merged