Added SharmaRajan json file in Submission folder
zero-to-mastery/ZtM-Job-Board pull request #3140
Opened 2024-02-03 09:24 UTC by SharmaRajan

2024-02-04 10:55 UTC, sophiabrandt requested changes

2024-02-04 10:55 UTC, sophiabrandt commented on Submissions/SharmaRajan.json
> +  "img": "[YOUR_IMG_URL]",
Please remove placeholder.

2024-02-04 10:55 UTC, sophiabrandt commented on Submissions/SharmaRajan.json
> +    "website": "[YOUR_WEBSITE_URL]",
Same here.

2024-02-18 15:00 UTC, sophiabrandt commented
@SharmaRajan can you please fix the above issues, so that we can merge your pull request?

2024-02-18 15:32 UTC, SharmaRajan commented
Removed the placeholder @sophiabrandt

2024-02-18 18:31 UTC, merged