added my file in Submissions
zero-to-mastery/ZtM-Job-Board pull request #3146
Opened 2024-02-09 17:58 UTC by RaduStana

2024-02-11 07:39 UTC, sophiabrandt requested changes

2024-02-11 07:39 UTC, sophiabrandt commented on Submissions/StanaR.json
> +  "img": "[YOUR_IMG_URL]",
Can you please remove the placeholders? You can just add an empty string:
```json
"img":  "",
```

2024-02-11 07:39 UTC, sophiabrandt commented on Submissions/StanaR.json
> +    "website": "[YOUR_WEBSITE_URL]",
Same here.

2024-03-02 12:37 UTC, sophiabrandt commented
@RaduStana are you still interested in this PR? Otherwise, I'll close it soon.

2024-03-02 14:29 UTC, RaduStana commented
Hello,
Yes, I am interested.
I have removed the placeholders.

În sâm., 2 mar. 2024 la 14:37, Sophia Brandt ***@***.***> a
scris:

> @RaduStana <https://github.com/RaduStana> are you still interested in
> this PR? Otherwise, I'll close it soon.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zero-to-mastery/ZtM-Job-Board/pull/3146#issuecomment-1974785940>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALXBJO42JSY2ENVZZQQCADTYWHBX7AVCNFSM6AAAAABDB3LDB6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNZUG44DKOJUGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-03 09:06 UTC, merged